# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: php

# The runtime the application uses.
type: "php:7.1"

# Configuration of the build of this application.
build:
    flavor: none

# The build-time dependencies of the app.
dependencies:
    php:
        drush/drush: "^8.0"
        phing/phing: "*"
    nodejs:
        grunt-cli: "~0.1.13"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysql:mysql"
    solr: "solr:solr"
#    redis: "redis:redis"

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        "/":
            # The folder to serve static assets for this location from.
            # (Relative to the application root.)
            root: "web"

            # How long to allow static assets from this location to be cached.
            # (Can be a time or -1 for no caching. Times can be suffixed with
            # "ms" (milliseconds), "s" (seconds), "m" (minutes), "h" (hours),
            # "d" (days), "w" (weeks), "M" (months, 30d) or "y" (years, 365d).)
            expires: -1

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            # (Can be true, false or a URI path string.)
            passthru: "/index.php"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/web/sites/default/files": "shared:files/files"
    "/web/sites/default/config": "shared:files/config"
    "/tmp": "shared:files/tmp"
    "/private": "shared:files/private"
    "/drush-backups": "shared:files/drush-backups"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
        set -e

        printf 'deploy.delete-sites = false' > build.properties
        composer config --global --auth http-basic.repo.packagist.com bimsonz b19c9f32a1966787021a55895f80792b70efb58e5ce3c339a48b85c3409b
        phing build:prepare
        composer update
        phing grunt:build

        cd web/sites/default/
        wget https://raw.githubusercontent.com/platformsh/platformsh-example-drupal8/master/web/sites/default/settings.php
        wget https://raw.githubusercontent.com/platformsh/platformsh-example-drupal8/master/web/sites/default/settings.platformsh.php
    # We run deploy hooks after your application has been deployed and started.
    deploy: |
        set -e

        # Re-install the site if this hasn't been installed yet for this branch, or we are on develop
        if [ $PLATFORM_ENVIRONMENT = "develop" ] || [ ! -f tmp/$PLATFORM_ENVIRONMENT.installed ]; then
          echo ">>> Re-installing CR profile"
          cd web/
          drush sql-drop -y
          drush si cr -y --account-pass='admin' --db-url=mysql://root@database.internal/main  install_configure_form.update_status_module='[FALSE, FALSE]' -y
          drush cr
          touch "tmp/${PLATFORM_ENVIRONMENT}.installed"
          echo ">>> End re-installing CR profile"
        else
          echo ">>> No re-installation of the profile required, just a simple update!"
          phing config:import
          cd web/
          drush cr
        fi

# The configuration of scheduled execution.
crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd web ; drush core-cron"
