# @file
# Template provided by https://github.com/LionsAd/drupal_ti.

language: php
php:
  - 5.6

git:
  depth: 1
sudo: false
cache:
  apt: true
  bundler: true
  directories:
    - $HOME/tmp/drush
    - $HOME/.bundle
    - $HOME/.composer
    - node_modules
    - vendor
rvm:
  - 2.1.5

matrix:
  fast_finish: true

env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"

    # Configuration variables.
    - DRUPAL_TI_MODULE_NAME="cr"
    #- DRUPAL_TI_SIMPLETEST_GROUP="commerce"

    # Define runners and environment vars to include before and after the
    # main runners / environment vars.
    #- DRUPAL_TI_SCRIPT_DIR_BEFORE="./drupal_ti/before"
    #- DRUPAL_TI_SCRIPT_DIR_AFTER="./drupal_ti/after"

    # The environment to use, supported are: drupal-7, drupal-8
    - DRUPAL_TI_ENVIRONMENT="drupal-8"

    # Drupal specific variables.
    - DRUPAL_TI_DB="drupal"
    - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal"
    # Note: Do not add a trailing slash here.
    - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
    - DRUPAL_TI_WEBSERVER_PORT="8080"

    # Simpletest specific commandline arguments, the DRUPAL_TI_SIMPLETEST_GROUP is appended at the end.
    - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT"

    # Code coverage via coveralls.io
    - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
    # This needs to match your .coveralls.yml file.
    - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"

    # Debug options
    #- DRUPAL_TI_DEBUG="-x -v"
    # Set to "all" to output all files, set to e.g. "xvfb selenium" or "selenium",
    # etc. to only output those channels.
    #- DRUPAL_TI_DEBUG_FILE_OUTPUT="selenium xvfb webserver"

    # - DRUPAL_TI_RUNNERS="behat"

    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"

    # Configuration variables.
    - export PROFILE="cr"
    - export DB="drupal"
    - export DB_URL="mysql://root:@127.0.0.1/drupal"
    - export BEHAT_DIR="./profiles/$PROFILE/tests/behat"
    - export BEHAT_DRIVER="phantomjs"
    - export BEHAT_BROWSER="firefox"
    # Note: Do not add a trailing slash here.
    - export WEBSERVER_URL="http://127.0.0.1"
    - export WEBSERVER_PORT="8080"

mysql:
  database: $DB
  username: root
  encoding: utf8

before_install:
  - rvm install 2.1.5
  - composer global config minimum-stability beta
  - composer global require phing/phing drush/drush:8.* lionsad/drupal_ti:1.4.4
  # Prepare environment
  - ./profiles/cr/tests/drupal_ti/scripts/before_install.sh
  - phing build:prepare
  # Check code quality before site is installed
  - drupal-ti --include profiles/cr/tests/drupal_ti/scripts/codecheck.sh

install:
  - drupal-ti install
  - drupal-ti --include profiles/cr/tests/drupal_ti/scripts/install.sh

before_script:
  - drupal-ti --include profiles/cr/tests/drupal_ti/scripts/before_script.sh

script:
  # Behat
  - drupal-ti --include profiles/cr/tests/drupal_ti/scripts/script.sh
  # Check DB errors
  - drupal-ti --include profiles/cr/tests/drupal_ti/scripts/dberrors.sh

notifications:
  slack: comicrelief:W1jExvqbSU9Kb3lyavdGHdGD
  # email: false
